# Pytorch version

In [2]:
import torch
print(torch.__version__)

2.11.0


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.3349, 0.1514, 0.1138],
        [0.9981, 0.8331, 0.6617]])

In [14]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 6))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])


## Tensor Shapes

In [24]:
x = torch.tensor([[1,2,3],[4,5,6]])
x


tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
y=torch.empty_like(x)
y

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.zeros_like(x,dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [32]:
x.dtype

torch.int64

## Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations


### 1. Scalar operation

In [35]:
# Returns a tensor filled with random numbers from a uniform distribution on the interval 
x = torch.rand(2,2)
x

tensor([[0.5557, 0.9770],
        [0.4440, 0.9478]])

In [38]:
# addition
print(x + 2)
# substraction
print(x - 2)
# multiplication
print(x * 3)
# division
print(x / 3)
# int division
print((x * 100)//3)
# mod
print(((x * 100)//3)%2)
# power
print(x**2)

tensor([[2.5557, 2.9770],
        [2.4440, 2.9478]])
tensor([[-1.4443, -1.0230],
        [-1.5560, -1.0522]])
tensor([[1.6672, 2.9311],
        [1.3321, 2.8435]])
tensor([[0.1852, 0.3257],
        [0.1480, 0.3159]])
tensor([[18., 32.],
        [14., 31.]])
tensor([[0., 0.],
        [0., 1.]])
tensor([[0.3089, 0.9546],
        [0.1972, 0.8984]])


### 2. Element wise operation

In [39]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])
tensor([[0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064]])


In [40]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.7445, 0.0657, 0.0060],
        [0.0377, 0.5277, 0.2472]])

In [41]:
c = torch.tensor([1, -2, 3, -4])
print(c)

tensor([ 1, -2,  3, -4])


In [42]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [45]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [47]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [48]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#tensor
e = torch.tensor([1.9, 2.3, 2.7, 2.8,4.4])

In [ ]:
# clamp: This operation is commonly used for activation constraints or keeping values within safe ranges during model training. 
torch.clamp(e, min=2, max=3)

tensor([2.0000, 2.3000, 2.7000, 2.8000, 3.0000])

### 3. Reduction operation


In [56]:
# This code creates a tensor filled with random integers between 0 and 9, but stores them as 32-bit floating-point numbers. 

f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
f

tensor([[8., 3., 6.],
        [1., 5., 5.]])